# -*- coding: utf-8 -*-
# Part of Tele. See LICENSE file for full copyright and licensing details.


{
    'name': 'Base',
    'version': '1.3',
    'category': 'Hidden',
    'description': """
The kernel of Tele, needed for all installation.
===================================================
""",
    'depends': [],
    'data': [
        'data/res_bank.xml',
        'data/res.lang.csv',
        'data/res_lang_data.xml',
        'data/res_partner_data.xml',
        'data/res_company_data.xml',
        'data/res_users_data.xml',
        'data/report_paperformat_data.xml',
        'data/res_currency_data.xml',
        'data/res_country_data.xml',
        'data/ir_demo_data.xml',
        'data/ir_config_parameter_data.xml',
        'security/base_groups.xml',
        'security/base_security.xml',
        'views/base_menus.xml',
        'views/decimal_precision_views.xml',
        'views/res_config_views.xml',
        'data/res.country.state.csv',
        'views/ir_actions_views.xml',
        'views/ir_asset_views.xml',
        'views/ir_config_parameter_views.xml',
        'views/ir_cron_views.xml',
        'views/ir_cron_trigger_views.xml',
        'views/ir_filters_views.xml',
        'views/ir_mail_server_views.xml',
        'views/ir_model_views.xml',
        'views/ir_attachment_views.xml',
        'views/ir_rule_views.xml',
        'views/ir_sequence_views.xml',
        'views/ir_translation_views.xml',
        'views/ir_ui_menu_views.xml',
        'views/ir_ui_view_views.xml',
        'views/ir_default_views.xml',
        'data/ir_cron_data.xml',
        'report/ir_model_report.xml',
        'report/ir_model_templates.xml',
        'views/ir_logging_views.xml',
        'views/ir_qweb_widget_templates.xml',
        'views/ir_module_views.xml',
        'data/ir_module_category_data.xml',
        'data/ir_module_module.xml',
        'report/ir_module_reports.xml',
        'report/ir_module_report_templates.xml',
        'wizard/base_module_update_views.xml',
        'wizard/base_language_install_views.xml',
        'wizard/base_import_language_views.xml',
        'wizard/base_module_upgrade_views.xml',
        'wizard/base_module_uninstall_views.xml',
        'wizard/base_export_language_views.xml',
        'wizard/base_update_translations_views.xml',
        'wizard/base_partner_merge_views.xml',
        'data/ir_actions_data.xml',
        'data/ir_demo_failure_data.xml',
        'views/ir_profile_views.xml',
        'views/res_company_views.xml',
        'views/res_lang_views.xml',
        'views/res_partner_views.xml',
        'views/res_bank_views.xml',
        'views/res_country_views.xml',
        'views/res_currency_views.xml',
        'views/res_users_views.xml',
        'views/ir_property_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_paperformat_views.xml',
        'views/onboarding_views.xml',
        'security/ir.model.access.csv',
        "views/res_users.xml", 
        "views/web.xml",
        "views/base_theme_setting.xml",
        "data/base_theme_data.xml",
      ],
    "assets": {
        "web.assets_frontend": [
            "/base/static/src/legacy/js/website_apps_menu.js",
            "/base/static/src/legacy/scss/website_apps_menu.scss",
            "/base/static/src/scss/login.scss",
        ],
        "web.assets_backend": [
            "/base/static/src/scss/base_theme_variables.scss",             
            "/base/static/src/legacy/scss/base.scss",
            "/base/static/src/legacy/js/base.js",
            "/base/static/src/legacy/scss/kanban_view_mobile.scss",
            "/base/static/src/legacy/js/kanban_renderer_mobile.js",
            "/base/static/src/components/ui_context.esm.js",
            "/base/static/src/components/apps_menu/apps_menu.scss",
            "/base/static/src/components/apps_menu/apps_menu.esm.js",
            "/base/static/src/components/navbar/main_navbar.scss",
            "/base/static/src/components/control_panel/control_panel.scss",
            "/base/static/src/components/control_panel/control_panel.esm.js",
            "/base/static/src/components/search_panel/search_panel.scss",
            "/base/static/src/components/search_panel/search_panel.esm.js",
            "/base/static/src/components/attachment_viewer/attachment_viewer.scss",
            "/base/static/src/components/attachment_viewer/attachment_viewer.esm.js",
            "/base/static/src/components/hotkey/hotkey.scss",
            "/base/static/src/scss/base_setting.scss",
            "/base/static/src/scss/style.scss",
            "/base/static/src/scss/dark_mode.scss",
            "/base/static/src/js/systray/systray_dark_mode_menu.js", 
        ],
        "web.assets_qweb": [
            "/base/static/src/xml/dark_mode.xml",
            "/base/static/src/legacy/xml/form_buttons.xml",
            "/base/static/src/components/apps_menu/apps_menu.xml",
            "/base/static/src/components/control_panel/control_panel.xml",
            "/base/static/src/components/navbar/main_navbar.xml",
            "/base/static/src/components/search_panel/search_panel.xml",
            "/base/static/src/components/attachment_viewer/attachment_viewer.xml",
            "/base/static/src/components/hotkey/hotkey.xml",    
            "/base/static/src/xml/systray_dark_mode_menu.xml",
            "/base/static/src/xml/pivot_view_inherit.xml",
      ],
        
    },
    'demo': [
        'data/res_company_demo.xml',
        'data/res_users_demo.xml',
        'data/res_partner_bank_demo.xml',
        'data/res_currency_rate_demo.xml',
        'data/res_bank_demo.xml',
        'data/res_partner_demo.xml',
        'data/res_partner_image_demo.xml',
    ],
    'test': [],
    'installable': True,
    'auto_install': True,
    'post_init_hook': 'post_init',
    'license': 'LGPL-3',
}
